<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/10/21 11:56:40
sfConfig::add(array(
  'app_upload_dir_name' => '/uploads',
  'app_content_attachments_path' => '/content/',
  'app_content_attachments_max_size' => 5000000,
  'app_content_import_path' => '/content_to_import/',
  'app_content_import_text_encoding' => 'UTF-8',
  'app_content_import_max_size' => 50000000,
  'app_culture_default' => 'en',
  'app_culture_list' => array (
  0 => 'ro',
  1 => 'da',
  2 => 'sv',
  3 => 'nb',
  4 => 'fr',
  5 => 'nl',
  6 => 'pl',
  7 => 'el',
  8 => 'pt',
  9 => 'ru',
  10 => 'es',
  11 => 'de',
  12 => 'en',
  13 => 'en_US',
  14 => 'hu',
),
));
