<?php


/**
 * Skeleton subclass for performing query and update operations on the 'config' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 05/13/11 15:20:01
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ConfigPeer extends BaseConfigPeer {

	public static function updateFreeGeneralVersion() {
		$config=self::getFreeGeneralVersion();
		if($config) {
			$config->setValue($config->getValue()+1);
			$config->save();
		}

	}

	public static function getFreeGeneralVersion() {
		$c=new Criteria();
		$c->add(self::CODE, 'free_general_version');
		$config=self::doSelectOne($c);
		return $config;
	}

} // ConfigPeer
