<?php


/**
 * Skeleton subclass for performing query and update operations on the 'content_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/24/11 17:47:54
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ContentI18nPeer extends BaseContentI18nPeer {

} // ContentI18nPeer
