<?php


/**
 * Skeleton subclass for representing a row from the 'content_sequence' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/14/11 16:05:02
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ContentSequence extends BaseContentSequence {

	const CONTENT_TYPE_BASE=0;
	const CONTENT_TYPE_ATTACHMENT=1;

} // ContentSequence
