<?php


/**
 * Skeleton subclass for representing a row from the 'content_attachment_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/24/11 17:47:55
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ContentAttachmentI18n extends BaseContentAttachmentI18n {

} // ContentAttachmentI18n
