<?php


/**
 * Skeleton subclass for representing a row from the 'content_i18n' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/24/11 17:47:54
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ContentI18n extends BaseContentI18n {

	/**
	 * Initializes internal state of ContentI18n object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}


} // ContentI18n
