<?php


/**
 * Skeleton subclass for performing query and update operations on the 'user' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/13/11 17:59:53
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UserPeer extends BaseUserPeer {

    public static function retrieveByLogin($login) {
    	$c=new Criteria();
    	$c->add(self::LOGIN, $login);
    	return self::doSelectOne($c);
	}

	public static function retrieveBySessionKey($sessionKey) {
    	if($sessionKey=='') return false;
    	$c=new Criteria();
    	$c->add(self::SESSION_KEY, $sessionKey);
    	return self::doSelectOne($c);
	}

	public static function generateUsers($loginPrefix, $startNumber, $amount) {
        $endNumber=$startNumber + $amount;
        for($i=$startNumber; $i<=$endNumber; $i++) {
        	$user=new User();
        	$user->generateLogin($i, $loginPrefix);
        	$user->generatePassword();
        	$user->save();
        }

    }
} // UserPeer
