<?php


/**
 * Skeleton subclass for representing a row from the 'user' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/13/11 17:59:53
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class User extends BaseUser {

	private static $passwordDictionary="qazxswedcvfrtgbnhyujmkiolp1234567890QAZXSWEDCVFRTGBNHYUJMKIOLP";

    public function generateSalt() {
		return rand(1000000, 9999999);

	}

	public function checkAuthHash($clientHash, $salt) {
		$serverHash=md5(md5($this->getLogin().$this->getPassword().$salt));
		return $serverHash==$clientHash;

	}

	public function getHash($salt) {
		return md5(md5($this->getLogin().$this->getPassword().$salt));
	}

	public function generateSessionKey() {
		$sessionKey=md5(rand(1000000, 9999999));
		$this->setSessionKey($sessionKey);
		$this->save();
		return $sessionKey;
	}

	public function getSecretKey() {
		$key=str_pad($this->getPassword(), 16, ' ', STR_PAD_LEFT);
		return $key;
	}

	public function generateLogin($login, $prefix='') {
		$login=$prefix.$login;
		$this->setLogin($login);
	    return $login;
	}

	public function generatePassword($length=8) {
		$password='';
		$dictionarySize=strlen(self::$passwordDictionary)-1;
		for($i=1; $i<=$length; $i++) {
			$password.=self::$passwordDictionary[rand(0,$dictionarySize)];
		}
		$this->setPassword($password);
	}

} // User
