<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/10/21 11:56:00

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=scotwork;host=localhost',
  'username' => 'scotwork',
  'password' => 'b5eijnkgbk9',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
